export const recentWorkAll = [
  {
    id: 1,
    title: "GPT-3 Landing",
    description: "Khow about GPT model in this landing",
    link: 'https://gpt3-clone-app-fz.netlify.app/',
    image: 'https://s2.uupload.ir/files/gap-3_image_ine.png',
    category: "all",
  },
  {
    id: 2,
    title: "Twitter Clone",
    description: "Tweet for all people around the world",
    link: 'https://twitter-clone-app-fz.netlify.app/',
    image: 'https://s2.uupload.ir/files/twitter_i74f.png',
    category: "all",
  },
  {
    id: 3,
    title: "Recipes App",
    description: "Take recipes from four country",
    link: 'https://recipes-app-fz.netlify.app/',
    image: 'https://s2.uupload.ir/files/recipes_xlm4.jpg',
    category: "all",
  },
  {
    id: 4,
    title: "WhastApp Clone",
    description: "Build rooms and enjouy talking onthers",
    link: 'https://whatsapp-clone-app-fz.netlify.app/',
    image: 'https://s2.uupload.ir/files/whatsapp_hr6r.jpg',
    category: "all",
  },
  {
    id: 5,
    title: "Slack Clone",
    description: "Want work together and chat? use this clone",
    link: 'https://slack-clone-app-fz.netlify.app/',
    image: 'https://s2.uupload.ir/files/slack_65xx.png',
    category: "all",
  },
  {
    id: 6,
    title: "Admin Panel",
    description: "manage user and product and see all deatails",
    link: 'https://lama-admin-panel.netlify.app/',
    image: 'https://s2.uupload.ir/files/adminpanel_v8q0.png',
    category: "all",
  },
];

export const recentWorkWeb = [
  {
    id: 1,
    title: "GPT-3 Landing",
    description: "Khow about GPT model in this landing",
    link: 'https://gpt3-clone-app-fz.netlify.app/',
    image: 'https://s2.uupload.ir/files/gap-3_image_ine.png',
    category: "web",
  },
  {
    id: 2,
    title: "Twitter Clone",
    description: "Tweet for all people around the world",
    link: 'https://twitter-clone-app-fz.netlify.app/',
    image: 'https://s2.uupload.ir/files/twitter_i74f.png',
    category: "web",
  },
  {
    id: 3,
    title: "Recipes App",
    description: "Take recipes from four country",
    link: 'https://recipes-app-fz.netlify.app/',
    image: 'https://s2.uupload.ir/files/recipes_xlm4.jpg',
    category: "web",
  },
  {
    id: 4,
    title: "WhastApp Clone",
    description: "Build rooms and enjouy talking onthers",
    link: 'https://whatsapp-clone-app-fz.netlify.app/',
    image: 'https://s2.uupload.ir/files/whatsapp_hr6r.jpg',
    category: "web",
  },
  {
    id: 5,
    title: "Slack Clone",
    description: "Want work together and chat? use this clone",
    link: 'https://slack-clone-app-fz.netlify.app/',
    image: 'https://s2.uupload.ir/files/slack_65xx.png',
    category: "web",
  },
  {
    id: 6,
    title: "Admin Panel",
    description: "manage user and product and see all deatails",
    link: 'https://lama-admin-panel.netlify.app/',
    image: 'https://s2.uupload.ir/files/adminpanel_v8q0.png',
    category: "web",
  },
];
